export const priceRange = [
  { price: "0-49", value: "$0 - $49" },
  { price: "50-99", value: "$50 - $99" },
  { price: "100-199", value: "$100 - $199" },
  { price: "200+", value: "$200 - $*" },
];

export const sizes = ["S", "M", "L", "XL"];

export const genders = ["male", "female", "unisex"];

const tailwindColorMap: Record<string, string> = {
  black: "bg-black",
  blue: "bg-blue-500",
  green: "bg-green-500",
  red: "bg-red-500",
  yellow: "bg-yellow-400",
  // ...
};

// Usage: casual - sports - ethnic
// Season: fall - summer - winter

const colors = [
  "beige",
  "black",
  "blue",
  "bronze",
  "brown",
  "charcoal",
  "coffee brown",
  "copper",
  "cream",
  "gold",
  "green",
  "grey",
  "khaki",
  "lavender",
  "magenta",
  "maroon",
  "multi",
  "navy blue",
  "off white",
  "olive",
  "orange",
  "peach",
  "pink",
  "purple",
  "red",
  "sea green",
  "silver",
  "steel",
  "tan",
  "teal",
  "white",
  "yellow",
];

export const subCategories = [
  "accessories",
  "apparel",
  "footwear",
  "personal care",
];

const tags = [
  "backpacks",
  "bath robe",
  "belts",
  "blazers",
  "boxers",
  "bra",
  "bracelet",
  "briefs",
  "camisoles",
  "capris",
  "caps",
  "casual shoes",
  "clutches",
  "deodorant",
  "dresses",
  "dupatta",
  "earrings",
  "face wash and cleanser",
  "flats",
  "flip flops",
  "formal shoes",
  "handbags",
  "heels",
  "innerwear vests",
  "jackets",
  "jeans",
  "jewellery set",
  "kurta sets",
  "kurtas",
  "laptop bag",
  "lip gloss",
  "lipstick",
  "lounge pants",
  "mufflers",
  "nail polish",
  "night suits",
  "pendant",
  "perfume and body mist",
  "rain jacket",
  "ring",
  "sandals",
  "sarees",
  "scarves",
  "shirts",
  "shoe accessories",
  "shorts",
  "shrug",
  "skirts",
  "socks",
  "sports shoes",
  "sunglasses",
  "sweatshirts",
  "tops",
  "track pants",
  "trousers",
  "trunk",
  "tshirts",
  "tunics",
  "waistcoat",
  "wallets",
  "watches",
];
